on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # UTC 17:00 -> CST (China) 1:00, see https://datetime360.com/cn/utc-cst-china-time/
    - cron: '0 0/9 * * *'
name: Mirror My GitHub Repos to Gitee
jobs:
  run:
    name: Sync-GitHub-to-Gitee
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1
    - name: Mirror the Github repos to Gitee.
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/yangtao521
        dst: gitee/yangt9264
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        mappings: ".github=>github"
        force_update: true
        static_list: "MoviePilot-Plugins-jxxghp,MoviePilot-Plugins-thsrite,MoviePilot-Frontend,MoviePilot,MoviePilot-Resources"
